name: Build & Test

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Free space
        run: df -h && rm -rf /opt/hostedtoolcache* && df -h

      - name: Pull Foundation Image
        uses: addnab/docker-run-action@v3
        with:
          image: quantconnect/lean:foundation

      - name: BuildDataSource
        run: dotnet build ./QuantConnect.DataSource.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

      - name: BuildDataProcessing
        run: dotnet build ./DataProcessing/DataProcessing.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

      - name: BuildTests
        run: dotnet build ./tests/Tests.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

      - name: Run Tests
        run: dotnet test ./tests/bin/Release/net6.0/Tests.dll --filter "TestCategory!=TravisExclude"
