name: Build & Test

on:
  push:
    branches: ['*']
    tags: ['*']
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
        image: quantconnect/lean:foundation
    steps:
      - uses: actions/checkout@v2

      - name: Checkout Lean
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          repository: QuantConnect/Lean
          path: Lean
      - name: Move Lean
        run: mv Lean ../Lean

      - name: BuildDataSource
        run: dotnet build ./QuantConnect.DataSource.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

      - name: BuildDataProcessing
        run: dotnet build ./DataProcessing/DataProcessing.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

      - name: BuildTests
        run: dotnet build ./tests/Tests.csproj /p:Configuration=Release /v:quiet /p:WarningLevel=1

      - name: Run Tests
        run: dotnet test ./tests/bin/Release/net5.0/Tests.dll
